export {default as Admin} from "./Admin";
export {default as Users} from "./Users";
export {default as Slides} from "./Slides";
export {default as Offers} from "./Offers";
export {default as Categories} from "./Categories";
export {default as Products} from "./Products";
export {default as News} from "./News";
export {default as Map} from "./Map";
export {default as MapImages} from "./MapImages";
